
# XM-Sim Command File
# TOOL:	xmsim	20.09-s001
#

set tcl_prompt1 {puts -nonewline "xcelium> "}
set tcl_prompt2 {puts -nonewline "> "}
set vlog_format %h
set vhdl_format %v
set real_precision 6
set display_unit auto
set time_unit module
set heap_garbage_size -200
set heap_garbage_time 0
set assert_report_level note
set assert_stop_level error
set autoscope yes
set assert_1164_warnings yes
set pack_assert_off {}
set severity_pack_assert_off {note warning}
set assert_output_stop_level failed
set tcl_debug_level 0
set relax_path_name 1
set vhdl_vcdmap XX01ZX01X
set intovf_severity_level ERROR
set probe_screen_format 0
set rangecnst_severity_level ERROR
set textio_severity_level ERROR
set vital_timing_checks_on 1
set vlog_code_show_force 0
set assert_count_attempts 1
set tcl_all64 false
set tcl_runerror_exit false
set assert_report_incompletes 0
set show_force 1
set force_reset_by_reinvoke 0
set tcl_relaxed_literal 0
set probe_exclude_patterns {}
set probe_packed_limit 4k
set probe_unpacked_limit 16k
set assert_internal_msg no
set svseed 1
set assert_reporting_mode 0
set vcd_compact_mode 0
alias . run
alias quit exit
database -open -shm -into waves.shm waves -default
probe -create -database waves top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HADDR top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HBURST top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HCLK top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HRDATA top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HREADYin top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HREADYout top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HRESETn top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HRESP top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HSEL top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HSIZE top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HTRANS top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HWDATA top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.HWRITE top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.T_ADDR top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.T_ADDRw top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.T_BE top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.T_BE_D top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.T_DATA top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.T_ENABLED top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.T_WR top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.T_WR_D top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.count top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.state top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_inst.xxy top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.ahb_fsm_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.ahb_fsm_reg_nxt top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.haddr_m_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.haddr_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hburst_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hclk_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hmastlock_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hprot_m_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hprot_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hrdata_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hready_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hresetn_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hresp_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hsize_m_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hsize_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.htrans_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hwdata_m_nxt top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hwdata_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hwrite_m_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.hwrite_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_addr_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_be_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_err_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_err_o_nxt top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_gnt_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_rdata_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_rdata_o_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_req_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_rvalid_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_wdata_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.instr_we_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.pending_dbus_xfer_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.prev_instr_gnt_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_inst.priv_mode_i
probe -create -database waves top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HADDR top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HBURST top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HCLK top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HRDATA top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HREADYin top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HREADYout top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HRESETn top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HRESP top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HSEL top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HSIZE top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HTRANS top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HWDATA top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.HWRITE top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.T_ADDR top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.T_ADDRw top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.T_BE top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.T_BE_D top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.T_DATA top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.T_ENABLED top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.T_WR top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.T_WR_D top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.count top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.state top_m2s1.cv32e40p_tb_wrapper_i.u_mem_ahb_data.xxy
probe -create -database waves top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.ahb_fsm_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.ahb_fsm_reg_nxt top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_addr_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_be_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_err_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_err_o_nxt top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_gnt_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_rdata_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_rdata_o_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_req_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_rvalid_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_wdata_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.data_we_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.haddr_m_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.haddr_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hburst_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hclk_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hmastlock_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hprot_m_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hprot_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hrdata_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hready_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hresetn_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hresp_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hsize_m_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hsize_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.htrans_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hwdata_m_nxt top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hwdata_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hwrite_m_reg top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.hwrite_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.pending_dbus_xfer_i top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.prev_data_gnt_o top_m2s1.cv32e40p_tb_wrapper_i.u_obi_ahb_bridge_data.priv_mode_i

simvision -input /home/kbkang/RISC-V_Testbench_CV32e40p/CV32e40p_Testbench_with_AHB_mem/.simvision/1425368_kbkang__autosave.tcl.svcf
